version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: c_mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Asdqwe123.'
    ports:
      - '1401:1433' 
    volumes:
      - mssql_data:/var/opt/mssql


  mongodb:
    image: mongo
    container_name: c_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: Asdqwe123.
    ports:
      - '27017:27017' 
    volumes:
      - mongo_data:/data/db


  postgres:
    image: postgres:latest
    container_name: c_postgres
    environment:
      POSTGRES_USER: sa_admin123
      POSTGRES_PASSWORD: Asdqwe123.
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: c_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: c_redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    restart: always


  consul:
    image: consul:1.15.4
    container_name: c_consul
    command: "agent -dev -client 0.0.0.0 -ui"
    ports:
      - '8500:8500'
    volumes:
      - consul_data:/consul/data

      
  adminer:
    image: adminer
    container_name: c_adminer
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - adminer_data:/adminer/data
  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: c_rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: always


volumes: 
  mssql_data:
  mongo_data:
  consul_data:
  adminer_data:  
  postgres_data:
  rabbit_data:  
  redis_data:
  redisinsight_data: